#!/bin/bash

# Jorge Vallejo Ortega - 04/06/2020 - Version 0.2

# This script reads the content of the directory,
# and formats the names of the files into csv.

# The goal is to get a list of files downloaded from Youtube
# into a format easily copied into 'Mediateca' spreadsheet.

# The final fields will be:
# <channel>;<title>;<file extension>


ls "$1" -N | # Print entry names without quoting
grep -E 'mp4$|mkv$' | # Recovers video files
#sed 's/-/;/' | # Change first hyphen for ;
sed 's/[[:alnum:]][[:alnum:]][[:alnum:]]$/;&/' | # Insert ; before file extension
sed 's/\.;/;/' # Get rid of the last dot
