#!/bin/bash

# Jorge Vallejo Ortega - 04/04/2020 - Version 2

# This script calls pandoc to transform a
# markdown document into an html document.

# Variable with the name of the target file
# from the name of the origin file
target=$(echo "$1" | sed 's/md/html/')

pandoc "$1" -f markdown -t html -o "$target"
