#!/bin/bash

# sincroniza_tostick -- script for sincronizing the UOC folder in Linux with
# the UOC folder in the pendrive.

# Jorge Vallejo - 16/02/2020 - version 4


# Beware, it deletes those files in destiny that are not longer in the origin.
# This first version (commented) is just a dry-run
# Since it sincronizes with an NTFS filesystem from an ext4(?) it is better not to compare permissions,
#   links, modification timestamps, ownership, nor special files and devices;
#   hence, the options: recursive, verbose, compress, human readable.

# Using $HOME and $USER variables so I can use it in any of my computers.

# Setting variables
desktop="$HOME"/EnUOC-master # Folder in desktop
USB=/media/"$USER"/KURONEKO/UOC-master # Folder in USB pendrive


# Check if origin and target directories exit
[ -d "$desktop" ] || { echo "El directorio $desktop no existe" >&2; exit 1; }

[ -d "$USB" ] || { echo "El directorio $USB no existe" >&2; exit 1; }


# Check if the user wants a dry run or a real run
if [ "$1" = '-d' ] || [ "$1" = '--dry' ]
then
    rsync -trvzhni --delete "$desktop"/ "$USB"
elif [ "$1" = '' ]
then
# This other version is the one that actually makes the changes
    rsync -trvzh --delete "$desktop"/ "$USB"
else
    echo 
    echo 'Option not found.'
    echo 'Please use -d, --dry, or nothing.'
    echo
fi

###TODO###

# Choose between desktop-to-stick or stick-to-desktop

# Make a call for help
