#!/bin/bash

# sincroniza_stick -- script for sincronizing the UOC folder in Linux with
# the UOC folder in the pendrive.

# Jorge Vallejo - 27/03/2020 - version 6


# Beware, it deletes those files in destiny that are not longer in the origin.
# This first version (commented) is just a dry-run
# Since it synchronises with an NTFS filesystem from an ext4(?) it is better not to compare permissions,
#   links, modification timestamps, ownership, nor special files and devices;
#   hence, the options: recursive, verbose, compress, human readable.

# Using $HOME and $USER variables so I can use it in any of my computers.

# Setting variables
desktop="$HOME"/EnUOC-master # Folder in desktop
USB=/media/"$USER"/KURONEKO/UOC-master # Folder in USB pendrive


# Check if origin and target directories exit
[ -d "$desktop" ] || { echo "El directorio $desktop no existe" >&2; exit 1; }

[ -d "$USB" ] || { echo "El directorio $USB no existe" >&2; exit 1; }


# Check if the user wants a dry run or a real run
if [ "$1" = '-n' ] || [ "$1" = '--dry' ]
then
    rsync -trvzhni --delete "$desktop"/ "$USB"
elif [ "$1" = '' ]
then
# This other version is the one that actually makes the changes
    rsync -trvzhi --delete "$desktop"/ "$USB"
# Synchronise *from* stick *to* computer (dry)
elif [ "$1" = '-rn' ] || [ "$1" = '--reverse-dry' ]
then
    rsync -trvzhni --delete "$USB"/ "$desktop"
elif [ "$1" = '-r' ] || [ "$1" = '--reverse' ]
then
    rsync -trvzhi --delete "$USB"/ "$desktop"
# Help text
elif [ "$1" = '-h' ] || [ "$1" = '--help' ]
then
    echo
    echo 'sincroniza_stick [OPTION]'
    echo 'No option: By default, synchronise from computer to pendrive.'
    echo '-n, --dry: Dry-run from computer to pendrive.'
    echo '-r, --reverse: Synchronise from pendrive to computer.'
    echo '-rn, --reverse-dry: Dry run from pendrive to computer.'
    echo '-h, --help: This text stating the options.'
    echo 
else
    echo 
    echo 'Option not found.'
    echo 'Please use -n (dry run), nothing (to stick), -rn (dry from stick), or -r (from stick)'
    echo
fi

###TODO###

# Make a call for help
